apiVersion: v1
kind: Service
metadata:
  name: speedjobs-backend
  namespace: skala-practice
spec:
  selector:
    app: speedjobs-backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

